apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: todoapps.todoapp.example.com
spec:
  version: 0.2.0
  group: todoapp.example.com
  names:
    kind: Todoapp
    listKind: TodoappList
    plural: todoapps
    singular: todoapp
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
