apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "todoapp.example.com/v1alpha1",
          "kind": "Todoapp",
          "metadata": {
            "name": "mytodo"
          },
          "spec": {
            "size": 1
          }
        }
      ]
    capabilities: Basic Install
  name: todoapp-operator.v0.2.0
  namespace: testoptodo
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Demo Only
      displayName: Todoapp Operator
      kind: Todoapp
      name: todoapps.todoapp.example.com
      version: v1alpha1
  displayName: Todoapp Operator
  icon:
     - base64data: iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAAVlQTFRFAAAAUojIUofIUIfHRX/EP3vCOW+wOW+vFShAFCg/UYfIUojIUojIUojIUojIUojIUojIUojIUojIUojIUIfIUojIUIjHU4nIUIfHUYfIRoDERX/EQHzCP3vCP3vCOXCwPnm/CxYjOG6uN2yqBgsSAAAAFixFNWikPXa6PXi9PHa6NWejFipCAAAAAwcLEyU6GTFOEiQ5AAAAAAAAAAAAAAAAAAAAAAAAAAAAUojIUIfIUIbHR4HFQn3DQX3DSIHFP3vCPnrCQHzCPXnBapnQscnmWo3KaZjP3uj0////zNzvWIzKWY3KvtLrPnvC7vL3g6jUQHzDPXrBepm+NmqoPnrAQXzDbJrQS4TGM2SeOnK0iq/a7/T6SYLF8fb7/f3+sMnmrcflSXy4s8Xa/v7+NmurQW2iPnm/NWqpaJfP+/3+wtXr3ej0QW6jprvUNmupNWScN22sP3vBdtn2zAAAADl0Uk5TAAAAAAAAAAAAAAMVHheQ1OHTjhYCiQEV0x7hHuEe4RbUB56VBwM6oNvn2pw4GzRETEMZBCkrGgEGUYakXgAAAAFiS0dESYcF5HwAAAAJcEhZcwAA7DgAAOw4AXEryjgAAAHLSURBVFjD7ddXU8JAEMBxqgUUu/RiwQ4WUARBiIgaC3Ys2BvYy/d/EAgtyd6GCw/OMO4z/99Qwt6cQtEYo9Tp26hHr1OV+3ZDRyf1dHX3KLle1WsIhpaoJxTs6+cEpdEUjixTTyRqMnKA2myJyRqLWV0ANFabPMBm1RQArd0hD3DYtf/AHwHMClMXEF9NrMXrAOLrG+zmVlw2kO/ZkiAD4PqSQA+U+pywzcgAKj3L7oST1EB1v7u3D76Dg2SN/eHRMQSkTk6Z2vqzc/BLTF8kLpmaezGQvmKvb2AB6kVArmcJAtgLgUIPC3AvAIo9JBB6PpC6Lb9GKJB6PsDc3T/AArEXfITHJ1gg9wIgkwUFpBf+CqCA9aLnABDQXvwkigS8B/4LAiH6jPbQ35knvLy+oT24UHgCi/fwRgIFuCesNEAg9KSdKBJIPXGpCgRiT97KPIHcI2u9SkB67FwoC1iPHixFAe3xkykvSPQSR1sm+/6B91JnY+bzC+8lD9fMN95Ln84/sToBqWkgoMnpkge4nM0FoGVgUB4wNNzKXdvcI6Nj49QzMTnlLl0cPd7pGeqZ9c6Vb64+j3+eevwLvsrdN+BbpB5foN4bNze/PgtQeiAPvjUAAAAldEVYdGRhdGU6Y3JlYXRlADIwMTgtMDMtMjNUMjA6NDU6MjIrMDE6MDBHANYJAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDE4LTAzLTIzVDIwOjQ1OjIyKzAxOjAwNl1utQAAAEZ0RVh0c29mdHdhcmUASW1hZ2VNYWdpY2sgNi43LjgtOSAyMDE2LTA2LTE2IFExNiBodHRwOi8vd3d3LmltYWdlbWFnaWNrLm9yZ+a/NLYAAAAYdEVYdFRodW1iOjpEb2N1bWVudDo6UGFnZXMAMaf/uy8AAAAYdEVYdFRodW1iOjpJbWFnZTo6aGVpZ2h0ADUxMsDQUFEAAAAXdEVYdFRodW1iOjpJbWFnZTo6V2lkdGgANTEyHHwD3AAAABl0RVh0VGh1bWI6Ok1pbWV0eXBlAGltYWdlL3BuZz+yVk4AAAAXdEVYdFRodW1iOjpNVGltZQAxNTIxODM0MzIyJT+dcgAAABN0RVh0VGh1bWI6OlNpemUANy41OUtCQqJZdXEAAAA/dEVYdFRodW1iOjpVUkkAZmlsZTovLy4vdXBsb2Fkcy81Ni9hdXM0R2wwLzEzODEvZ25vbWV0b2RvXzk0NjM3LnBuZ16KtoIAAAAASUVORK5CYII=
       mediatype: image/svg+xml
  install:
    spec:
      deployments:
      - name: todoapp-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: todoapp-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: todoapp-operator
            spec:
              containers:
              - command:
                - /usr/local/bin/ao-logs
                - /tmp/ansible-operator/runner
                - stdout
                image: quay.io/jaysonzhao/todoapp-operator:v0.1.5
                imagePullPolicy: Always
                name: ansible
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
                  readOnly: true
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: todoapp-operator
                - name: ANSIBLE_GATHERING
                  value: explicit
                image: quay.io/jaysonzhao/todoapp-operator:v0.1.5
                imagePullPolicy: Always
                name: operator
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
              serviceAccountName: todoapp-operator
              volumes:
              - emptyDir: {}
                name: runner
      permissions:
      - rules:
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - todoapp-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - todoapp.example.com
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: todoapp-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider:
    name: Jayson Zhao
  replaces: todoapp-operator.v0.0.0
  version: 0.2.0
